services:
  redis:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
